/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as BulkSupplyRouteImport } from './routes/bulk-supply'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DistributorsRouteImport } from './routes/distributors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as IndustriesHotelsRouteImport } from './routes/industries/hotels'
import { Route as IndustriesRestaurantsRouteImport } from './routes/industries/restaurants'
import { Route as IndustriesSupermarketsRouteImport } from './routes/industries/supermarkets'
import { Route as IndustriesWholesalersRouteImport } from './routes/industries/wholesalers'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as Products1lPalmOilRouteImport } from './routes/products/1l-palm-oil'
import { Route as Products25lPalmOilRouteImport } from './routes/products/25l-palm-oil'
import { Route as Products3lPalmOilRouteImport } from './routes/products/3l-palm-oil'
import { Route as Products500mlPalmOilRouteImport } from './routes/products/500ml-palm-oil'
import { Route as Products5lPalmOilRouteImport } from './routes/products/5l-palm-oil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkSupplyRoute = BulkSupplyRouteImport.update({
  id: '/bulk-supply',
  path: '/bulk-supply',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorsRoute = DistributorsRouteImport.update({
  id: '/distributors',
  path: '/distributors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHotelsRoute = IndustriesHotelsRouteImport.update({
  id: '/industries/hotels',
  path: '/industries/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRestaurantsRoute = IndustriesRestaurantsRouteImport.update({
  id: '/industries/restaurants',
  path: '/industries/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSupermarketsRoute = IndustriesSupermarketsRouteImport.update({
  id: '/industries/supermarkets',
  path: '/industries/supermarkets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesWholesalersRoute = IndustriesWholesalersRouteImport.update({
  id: '/industries/wholesalers',
  path: '/industries/wholesalers',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const Products1lPalmOilRoute = Products1lPalmOilRouteImport.update({
  id: '/1l-palm-oil',
  path: '/1l-palm-oil',
  getParentRoute: () => ProductsRoute,
} as any)
const Products25lPalmOilRoute = Products25lPalmOilRouteImport.update({
  id: '/25l-palm-oil',
  path: '/25l-palm-oil',
  getParentRoute: () => ProductsRoute,
} as any)
const Products3lPalmOilRoute = Products3lPalmOilRouteImport.update({
  id: '/3l-palm-oil',
  path: '/3l-palm-oil',
  getParentRoute: () => ProductsRoute,
} as any)
const Products500mlPalmOilRoute = Products500mlPalmOilRouteImport.update({
  id: '/500ml-palm-oil',
  path: '/500ml-palm-oil',
  getParentRoute: () => ProductsRoute,
} as any)
const Products5lPalmOilRoute = Products5lPalmOilRouteImport.update({
  id: '/5l-palm-oil',
  path: '/5l-palm-oil',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/bulk-supply': typeof BulkSupplyRoute
  '/contact': typeof ContactRoute
  '/distributors': typeof DistributorsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/quality': typeof QualityRoute
  '/industries/hotels': typeof IndustriesHotelsRoute
  '/industries/restaurants': typeof IndustriesRestaurantsRoute
  '/industries/supermarkets': typeof IndustriesSupermarketsRoute
  '/industries/wholesalers': typeof IndustriesWholesalersRoute
  '/products/1l-palm-oil': typeof Products1lPalmOilRoute
  '/products/25l-palm-oil': typeof Products25lPalmOilRoute
  '/products/3l-palm-oil': typeof Products3lPalmOilRoute
  '/products/500ml-palm-oil': typeof Products500mlPalmOilRoute
  '/products/5l-palm-oil': typeof Products5lPalmOilRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/bulk-supply': typeof BulkSupplyRoute
  '/contact': typeof ContactRoute
  '/distributors': typeof DistributorsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/quality': typeof QualityRoute
  '/industries/hotels': typeof IndustriesHotelsRoute
  '/industries/restaurants': typeof IndustriesRestaurantsRoute
  '/industries/supermarkets': typeof IndustriesSupermarketsRoute
  '/industries/wholesalers': typeof IndustriesWholesalersRoute
  '/products/1l-palm-oil': typeof Products1lPalmOilRoute
  '/products/25l-palm-oil': typeof Products25lPalmOilRoute
  '/products/3l-palm-oil': typeof Products3lPalmOilRoute
  '/products/500ml-palm-oil': typeof Products500mlPalmOilRoute
  '/products/5l-palm-oil': typeof Products5lPalmOilRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/bulk-supply': typeof BulkSupplyRoute
  '/contact': typeof ContactRoute
  '/distributors': typeof DistributorsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/quality': typeof QualityRoute
  '/industries/hotels': typeof IndustriesHotelsRoute
  '/industries/restaurants': typeof IndustriesRestaurantsRoute
  '/industries/supermarkets': typeof IndustriesSupermarketsRoute
  '/industries/wholesalers': typeof IndustriesWholesalersRoute
  '/products/1l-palm-oil': typeof Products1lPalmOilRoute
  '/products/25l-palm-oil': typeof Products25lPalmOilRoute
  '/products/3l-palm-oil': typeof Products3lPalmOilRoute
  '/products/500ml-palm-oil': typeof Products500mlPalmOilRoute
  '/products/5l-palm-oil': typeof Products5lPalmOilRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bootstrap'
    | '/bulk-supply'
    | '/contact'
    | '/distributors'
    | '/login'
    | '/products'
    | '/quality'
    | '/industries/hotels'
    | '/industries/restaurants'
    | '/industries/supermarkets'
    | '/industries/wholesalers'
    | '/products/1l-palm-oil'
    | '/products/25l-palm-oil'
    | '/products/3l-palm-oil'
    | '/products/500ml-palm-oil'
    | '/products/5l-palm-oil'
    | '/industries/'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/bootstrap'
    | '/bulk-supply'
    | '/contact'
    | '/distributors'
    | '/login'
    | '/products'
    | '/quality'
    | '/industries/hotels'
    | '/industries/restaurants'
    | '/industries/supermarkets'
    | '/industries/wholesalers'
    | '/products/1l-palm-oil'
    | '/products/25l-palm-oil'
    | '/products/3l-palm-oil'
    | '/products/500ml-palm-oil'
    | '/products/5l-palm-oil'
    | '/industries'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bootstrap'
    | '/bulk-supply'
    | '/contact'
    | '/distributors'
    | '/login'
    | '/products'
    | '/quality'
    | '/industries/hotels'
    | '/industries/restaurants'
    | '/industries/supermarkets'
    | '/industries/wholesalers'
    | '/products/1l-palm-oil'
    | '/products/25l-palm-oil'
    | '/products/3l-palm-oil'
    | '/products/500ml-palm-oil'
    | '/products/5l-palm-oil'
    | '/industries/'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BootstrapRoute: typeof BootstrapRoute
  BulkSupplyRoute: typeof BulkSupplyRoute
  ContactRoute: typeof ContactRoute
  DistributorsRoute: typeof DistributorsRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QualityRoute: typeof QualityRoute
  IndustriesHotelsRoute: typeof IndustriesHotelsRoute
  IndustriesRestaurantsRoute: typeof IndustriesRestaurantsRoute
  IndustriesSupermarketsRoute: typeof IndustriesSupermarketsRoute
  IndustriesWholesalersRoute: typeof IndustriesWholesalersRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-supply': {
      id: '/bulk-supply'
      path: '/bulk-supply'
      fullPath: '/bulk-supply'
      preLoaderRoute: typeof BulkSupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributors': {
      id: '/distributors'
      path: '/distributors'
      fullPath: '/distributors'
      preLoaderRoute: typeof DistributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/hotels': {
      id: '/industries/hotels'
      path: '/industries/hotels'
      fullPath: '/industries/hotels'
      preLoaderRoute: typeof IndustriesHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/restaurants': {
      id: '/industries/restaurants'
      path: '/industries/restaurants'
      fullPath: '/industries/restaurants'
      preLoaderRoute: typeof IndustriesRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/supermarkets': {
      id: '/industries/supermarkets'
      path: '/industries/supermarkets'
      fullPath: '/industries/supermarkets'
      preLoaderRoute: typeof IndustriesSupermarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/wholesalers': {
      id: '/industries/wholesalers'
      path: '/industries/wholesalers'
      fullPath: '/industries/wholesalers'
      preLoaderRoute: typeof IndustriesWholesalersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/1l-palm-oil': {
      id: '/products/1l-palm-oil'
      path: '/1l-palm-oil'
      fullPath: '/products/1l-palm-oil'
      preLoaderRoute: typeof Products1lPalmOilRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/25l-palm-oil': {
      id: '/products/25l-palm-oil'
      path: '/25l-palm-oil'
      fullPath: '/products/25l-palm-oil'
      preLoaderRoute: typeof Products25lPalmOilRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/3l-palm-oil': {
      id: '/products/3l-palm-oil'
      path: '/3l-palm-oil'
      fullPath: '/products/3l-palm-oil'
      preLoaderRoute: typeof Products3lPalmOilRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/500ml-palm-oil': {
      id: '/products/500ml-palm-oil'
      path: '/500ml-palm-oil'
      fullPath: '/products/500ml-palm-oil'
      preLoaderRoute: typeof Products500mlPalmOilRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/5l-palm-oil': {
      id: '/products/5l-palm-oil'
      path: '/5l-palm-oil'
      fullPath: '/products/5l-palm-oil'
      preLoaderRoute: typeof Products5lPalmOilRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  Products1lPalmOilRoute: typeof Products1lPalmOilRoute
  Products25lPalmOilRoute: typeof Products25lPalmOilRoute
  Products3lPalmOilRoute: typeof Products3lPalmOilRoute
  Products500mlPalmOilRoute: typeof Products500mlPalmOilRoute
  Products5lPalmOilRoute: typeof Products5lPalmOilRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  Products1lPalmOilRoute: Products1lPalmOilRoute,
  Products25lPalmOilRoute: Products25lPalmOilRoute,
  Products3lPalmOilRoute: Products3lPalmOilRoute,
  Products500mlPalmOilRoute: Products500mlPalmOilRoute,
  Products5lPalmOilRoute: Products5lPalmOilRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BootstrapRoute: BootstrapRoute,
  BulkSupplyRoute: BulkSupplyRoute,
  ContactRoute: ContactRoute,
  DistributorsRoute: DistributorsRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QualityRoute: QualityRoute,
  IndustriesHotelsRoute: IndustriesHotelsRoute,
  IndustriesRestaurantsRoute: IndustriesRestaurantsRoute,
  IndustriesSupermarketsRoute: IndustriesSupermarketsRoute,
  IndustriesWholesalersRoute: IndustriesWholesalersRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
